# Base configs
baseurl: ""
url: "http://photography.ramswaroop.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Matt Francis"
subtitle: "See the world through my eyes!"
author: "Matt Francis"
bio: "I am a student from London, and I am learning photography through this site."
publicise: ""
web_design: "Matt"
social_urls:
  twitter: "https://www.twitter.com/mfrancisphotos"
  instagram: "https://www.instagram.com/mattfrancisphoto"

  
